language: python

python:
    - "2.7"

sudo: enabled

install:
  - pip install -r requirements.txt

before_script:
  - python setup.py build
  - export PATH=$PATH:$TRAVIS_BUILD_DIR

script:
  - make
  - make test
